version: "3"
services:
  depot_database:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: depot_database
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: depot_user
      MYSQL_PASSWORD: depot_password
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
